### ISSUE TITLE
ShopSearchMysql: Column 'Title' in where clause is ambiguous

### ISSUE THREAD

**Issue by hex0id** [markguinn/silverstripe-shop-search#2]
I am trying hard to set this up, but with no success. Here's configuration:

```
Tour:
  extensions:
    - HasStaticAttributes
    - ProductCategoryHelperMethods
    - VirtualFieldIndex

ShopSearch:
  adapter_class: ShopSearchMysql
  searchable:
    - Tour
  facets:
    Price:
      Label: Price
      Type: range
      MinValue: 0
      MaxValue: 2000
      RangeMin: 0
      RangeMax: 2000
      LabelFormat: Currency
  sort_options:
    'score desc': 'Relevance'
    'SiteTree_Title asc': 'Alphabetical'

Destination_Controller:
  extensions:
    - FacetedCategory

VirtualFieldIndex:
  vfi_spec:
    Tour:
      Price:
        Type: simple
        Source: getPerPersonPrice
        DependsOn: all
        DBField: Currency
      Categories:
        Type: list
        DependsOn: all
        Source:
          - ParentID
          - ProductCategories.ID

FacetedCategory:
  facets:
    Price:
      Label: Price
      Type: range
      MinValue: 0
      MaxValue: 2000
      RangeMin: 0
      RangeMax: 2000
      LabelFormat: Currency
  auto_facet_attributes: true
  products_method: ToursShowable
```

Tour is direct subclass of Product.

Tour has necessary things:

```
    private static $indexes = array(
        'Featured' => true,
        'AllowPurchase' => true,
        'InternalItemID' => true,
        'SearchFields' => array(
            'type' => 'fulltext',
            'name' => 'SearchFields',
            'value' => 'Title'
        )
    );
```

and

```
    private static $searchable_fields = array(
        'Title', 'Content', 'InternalItemID','Featured'
    );
```

All I get is:

```
Couldn't run query: SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."Created", "SiteTree_Live"."LastEdited", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Locale", "SiteTree_Live"."ProvideComments", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "Page_Live"."InheritSidebar", "Page_Live"."InheritFooterColumn1", "Page_Live"."InheritFooterColumn2", "Page_Live"."InheritFooterColumn3", "Page_Live"."InheritFooterColumn4", "Page_Live"."SidebarID", "Page_Live"."FooterColumn1ID", "Page_Live"."FooterColumn2ID", "Page_Live"."FooterColumn3ID", "Page_Live"."FooterColumn4ID", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."InternalItemID" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."InternalItemID" ELSE NULL END AS "InternalItemID", "Product_Live"."Model", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."CostPrice" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."CostPrice" ELSE NULL END AS "CostPrice", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."BasePrice" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."BasePrice" ELSE NULL END AS "BasePrice", "Product_Live"."Weight", "Product_Live"."Height", "Product_Live"."Width", "Product_Live"."Depth", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."Featured" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."Featured" ELSE NULL END AS "Featured", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."AllowPurchase" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."AllowPurchase" ELSE NULL END AS "AllowPurchase", CASE WHEN "SiteTree_Live"."ClassName" IN ('Product', 'Tour') THEN "Product_Live"."Popularity" WHEN "SiteTree_Live"."ClassName" IN ('Tour') THEN "Tour_Live"."Popularity" ELSE NULL END AS "Popularity", "Product_Live"."ImageID", "Tour_Live"."Lat", "Tour_Live"."Lng", "Tour_Live"."Address", "Tour_Live"."Suburb", "Tour_Live"."State", "Tour_Live"."Postcode", "Tour_Live"."Country", "Tour_Live"."VFI_Price", "Tour_Live"."VFI_Categories", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" LEFT JOIN "Page_Live" ON "Page_Live"."ID" = "SiteTree_Live"."ID" LEFT JOIN "Product_Live" ON "Product_Live"."ID" = "SiteTree_Live"."ID" LEFT JOIN "Tour_Live" ON "Tour_Live"."ID" = "SiteTree_Live"."ID" WHERE (MATCH (Title) AGAINST ('fcusa')) AND ("SiteTree_Live"."ParentID" = '48') AND ("SiteTree_Live"."ClassName" IN ('Tour')) AND ("SiteTree_Live"."Locale" = 'en_US') ORDER BY "SiteTree_Live"."Title" ASC Column 'Title' in where clause is ambiguous
```
